// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/liwaisi-tech/iot-hub-center/backends/go-mqtt-subscriber/internal/domain/messages/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewTempHumidityServiceMock creates a new instance of TempHumidityServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTempHumidityServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TempHumidityServiceMock {
	mock := &TempHumidityServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TempHumidityServiceMock is an autogenerated mock type for the TempHumidityService type
type TempHumidityServiceMock struct {
	mock.Mock
}

type TempHumidityServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TempHumidityServiceMock) EXPECT() *TempHumidityServiceMock_Expecter {
	return &TempHumidityServiceMock_Expecter{mock: &_m.Mock}
}

// ProcessTempHumidityMessage provides a mock function for the type TempHumidityServiceMock
func (_mock *TempHumidityServiceMock) ProcessTempHumidityMessage(message *entities.TempHumidityEntity) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTempHumidityMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.TempHumidityEntity) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TempHumidityServiceMock_ProcessTempHumidityMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTempHumidityMessage'
type TempHumidityServiceMock_ProcessTempHumidityMessage_Call struct {
	*mock.Call
}

// ProcessTempHumidityMessage is a helper method to define mock.On call
//   - message
func (_e *TempHumidityServiceMock_Expecter) ProcessTempHumidityMessage(message interface{}) *TempHumidityServiceMock_ProcessTempHumidityMessage_Call {
	return &TempHumidityServiceMock_ProcessTempHumidityMessage_Call{Call: _e.mock.On("ProcessTempHumidityMessage", message)}
}

func (_c *TempHumidityServiceMock_ProcessTempHumidityMessage_Call) Run(run func(message *entities.TempHumidityEntity)) *TempHumidityServiceMock_ProcessTempHumidityMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.TempHumidityEntity))
	})
	return _c
}

func (_c *TempHumidityServiceMock_ProcessTempHumidityMessage_Call) Return(err error) *TempHumidityServiceMock_ProcessTempHumidityMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TempHumidityServiceMock_ProcessTempHumidityMessage_Call) RunAndReturn(run func(message *entities.TempHumidityEntity) error) *TempHumidityServiceMock_ProcessTempHumidityMessage_Call {
	_c.Call.Return(run)
	return _c
}
