// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/liwaisi-tech/iot-hub-center/backends/go-mqtt-subscriber/internal/domain/messages/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewTempHumidityUseCaseMock creates a new instance of TempHumidityUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTempHumidityUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TempHumidityUseCaseMock {
	mock := &TempHumidityUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TempHumidityUseCaseMock is an autogenerated mock type for the TempHumidityUseCase type
type TempHumidityUseCaseMock struct {
	mock.Mock
}

type TempHumidityUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TempHumidityUseCaseMock) EXPECT() *TempHumidityUseCaseMock_Expecter {
	return &TempHumidityUseCaseMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type TempHumidityUseCaseMock
func (_mock *TempHumidityUseCaseMock) Execute(message *entities.TempHumidityEntity) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.TempHumidityEntity) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TempHumidityUseCaseMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type TempHumidityUseCaseMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - message
func (_e *TempHumidityUseCaseMock_Expecter) Execute(message interface{}) *TempHumidityUseCaseMock_Execute_Call {
	return &TempHumidityUseCaseMock_Execute_Call{Call: _e.mock.On("Execute", message)}
}

func (_c *TempHumidityUseCaseMock_Execute_Call) Run(run func(message *entities.TempHumidityEntity)) *TempHumidityUseCaseMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.TempHumidityEntity))
	})
	return _c
}

func (_c *TempHumidityUseCaseMock_Execute_Call) Return(err error) *TempHumidityUseCaseMock_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TempHumidityUseCaseMock_Execute_Call) RunAndReturn(run func(message *entities.TempHumidityEntity) error) *TempHumidityUseCaseMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}
